config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users
  resources :users
  resources :rooms
  post 'reserves/new', to: 'reserves#new'
  post 'reserves/create', to: 'reserves#create'
  resources :reserves
  get "search" => "searches#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reserve.rb
class Reserve < ApplicationRecord
  
  validates_acceptance_of :confirming
  after_validation :check_confirming

  def check_confirming
    errors.delete(:confirming)
    self.confirming = errors.empty? ? '1' : ''
  end
  
  belongs_to :user, optional: true
  belongs_to :room, optional: true
  has_one_attached :room_img
  has_many :users

end

app/models/room.rb
class Room < ApplicationRecord

  validates :room_name, presence: true
  validates :room_detail, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :room_img, presence: true
  
  belongs_to :user, optional: true
  belongs_to :reserve, optional: true
  has_one_attached :room_img
  has_many :reserves

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  belongs_to :room, optional: true
  belongs_to :reserve, optional: true
  has_one_attached :user_img

  has_many :rooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  def set_search
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :user_img])
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  before_action :authenticate_user!

  def index
    @reserves = Reserve.all
    @user = current_user
    @rooms = Room.all  
  end

  def new
    @room = Room.find(params[:reserve][:room_id])
    @reserve = Reserve.new(reserve_params)
    @price = @room.price * @reserve.people * (@reserve.end_date - @reserve.start_date).to_i
    @days =  (@reserve.end_date - @reserve.start_date).to_i
  end

  def create
    @room = Room.find(params[:reserve][:room_id])
    @reserve = Reserve.create(reserve_params)
    @price = @room.price * @reserve.people * (@reserve.end_date - @reserve.start_date).to_i
    if @reserve.save
      @room = Room.find(params[:reserve][:room_id])
      redirect_to reserf_path(@reserve.id)
    else
      render :new
    end
  end

  def show
    @reserve = Reserve.find(params[:id])
    @price = @reserve.room.price * @reserve.people * (@reserve.end_date - @reserve.start_date).to_i

  end

    private
  def reserve_params
    params.require(:reserve).permit(:start_date, :end_date, :people, :room_id, :user_id, :confirming).merge(user_id: current_user.id, room_id: (params[:reserve][:room_id]))
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.create(room_params)
    @room.user_id = current_user.id
    if @room.save
      redirect_to room_path(@room)
    else
      render :new
    end
  end

  def show
    @room = Room.find(params[:id])
    @reserve = Reserve.new
  end

  def edit
  end

  private
  def room_params
    params.require(:room).permit(:room_name, :room_detail, :price, :address, :room_img)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, only: [:update]

  protected

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, user_img])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit 
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :email, :profile, :user_img)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class = main>
  <h1>好きな場所やキーワードを検索して　宿を借りよう</h1>

  <%= search_form_for @q, class: "search_list" do |f| %>
    <%= f.label :エリア検索 %>
    <%= f.search_field :address_cont, placeholder: '東京' %>
    <% f.submit %>
  <% end %>

  <%= search_form_for @q, class: "search_list" do |f| %>
    <%= f.label :部屋一覧を見てみる %>
    <%= f.submit "一覧へ" %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Syukuhakuapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <header>  
      <div class ="header_content">
        <ul>
          <li>
            <%= link_to root_path do %>
              <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png" alt="poteshare" title="poteshare">
            <% end %>
          </li>
          <% if user_signed_in? %>
            <li>   
              <%= link_to user_path(current_user), class: "navbar_name" do %>
                <% if current_user.user_img.attached? %>
                  <%= image_tag current_user.user_img, size: '80x80' %>
                <% else %>  
                  <%= image_tag "no_image.png", size: '80x80' %>
                <% end %>
            </li> 
            <li class = navbar_name >
              <%= current_user.user_name %>
            </li>
              <% end %>

                  <li>
                    <%= link_to new_room_path, class: "navbar_item" do %>
                      <p>部屋の新規登録</p>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to reserves_path, class: "navbar_item" do %>
                      <p>予約一覧</p>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to destroy_user_session_path, method: :delete, class: "navbar_item" do %>
                      <p>ログアウト</p>
                    <% end %>
                  </li>
              
            <% else %>
                  <li>
                    <%= link_to new_user_registration_path, class: "navbar_item" do %>
                    <p>新規登録</p>
                    <% end %>
                  </li>

                  <li>
                    <%= link_to new_user_session_path, class: "navbar_item" do %>
                    <p>ログイン</p>
                    <% end %>
                  </li>
              <% end %> 
          </ul>  
      </div>  

      <div class = header_search>
        <%= search_form_for @q, class: "search_list" do |f| %>
          <ul>
            <li>
              <%= f.search_field :address_cont, placeholder: 'エリア' %>
                </br>
              <%= f.submit "エリア検索"%>
            </li>

            <li>
              <%= f.search_field :room_name_or_room_detail_cont, placeholder: 'キーワード' %>
                </br>
              <%= f.submit "キーワード検索" %>
            </li>
          </ul>  
        <% end %>
      </div>

        <div class = main_content>
          <p></p>
        </div>
    
    </header>
      <%= yield %>
  
  </body>
</html>

app/views/reserves/creae.html.erb
<h1>Reserves#creae</h1>
<p>Find me in app/views/reserves/creae.html.erb</p>

app/views/reserves/index.html.erb
<h3>予約一覧</h3>

<% @reserves.each do |reserve| %>
  <div class = reserve_index>
    <%= link_to room_path(reserve.room_id), class: "index_content" do %>
      <ul>
        <li>
          <p class = room_index_tag>部屋画像</p>
            <% if reserve.room.room_img.attached? %>
              <%= image_tag reserve.room.room_img, size: '200x200' %>
            <% else %>  
              <%= image_tag "no_image.png", size: '200x200' %>
            <% end %>
        </li>
        <li>
          <p class = room_index_tag>部屋の名前</p>
          <%= reserve.room.room_name %>
        </li>
        <li>
          <p class = room_index_tag>部屋の説明</p>
          <%= reserve.room.room_detail %>
        </li>
        <li>
          <p class = room_index_tag>合計金額</p>
          <%= reserve.room.price.to_i * reserve.people * (reserve.end_date - reserve.start_date).to_i %>円
        </li>
        <li>
          <p class = room_index_tag>開始日</p>
          <%= reserve.start_date %>
        </li>
        <li>
          <p class = room_index_tag>終了日</p>
          <%= reserve.end_date %>
        </li>
        <li>
          <p class = room_index_tag>予約確定日</p>
          <%= reserve.created_at.to_s(:datetime_jp) %>
        </li>
      </ul>
    <% end %>
  </div>
<% end %>

app/views/reserves/new.html.erb
<h3>予約内容確認</h3>


<%= form_for @reserve do |f| %>
  <% if @reserve.confirming.blank? %>
    <div class = reserve_new>
      <ul>
        <li>
          <%= f.label :開始日 %>
          ：<%= @reserve.start_date %>
          <%= f.hidden_field :start_date %> 
        </li>

        <li>
          <%= f.label :終了日 %>
          ：<%= @reserve.end_date %>
          <%= f.hidden_field :end_date %> 
        </li>

        <li>
          <%= f.label :人数 %>
          ：<%= @reserve.people %>人
          <%= f.hidden_field :people %> 
        </li>
        <li>
          <%= f.label :使用日数 %>
          ：<%= @days %>日間
        </li>
        <li>
          <%= f.label :合計金額 %>
          ￥<%=  @price %>
        </li>
      </ul>
  <% else %>
      <ul>
        <li>
          <%= f.label :開始日 %>
          ：<%= @reserve.start_date.strftime("%Y年%m月%d日") %>
          <%= f.hidden_field :start_date %> 
        </li>
        <li>
          <%= f.label :終了日 %>
          ：<%= @reserve.end_date.strftime("%Y年%m月%d日") %>
          <%= f.hidden_field :end_date %> 
        </li>
        <li>
          <%= f.label :人数 %>
          ：<%= @reserve.people %>人
          <%= f.hidden_field :people %> 
        </li>
        <li>
          <%= f.label :使用日数 %>
          ：<%= @days %>日間
        </li>
        <li>
          <%= f.label :合計金額 %>
          ￥<%=  @price %>
        </li>
      </ul>
  <% end %>
    </div>


  <%= f.hidden_field :room_id, value: @room.id %> 

  <p>以上の内容でよろしければ確定ボタンを押してください</p>

  <%= f.submit "予約を確定する" %>

  <%=link_to room_path(@reserve.room_id) do %>
    <button class="btn btn-secondary btn-lg" >部屋詳細に戻る</button>
  <%end%>

<% end %>

app/views/reserves/show.html.erb
<h3>予約が完了しました</h3>
  
<div class = reserve_show>
  <%= link_to room_path(@reserve.room_id), class: "index_content" do %>
    <ul>
      <li>
        <p>予約した部屋：<%= @reserve.room.room_name %></p>
      </li>
      <li>
        <p>開始日：<%= @reserve.start_date %></p>
      </li>
      <li>
        <p>終了日：<%= @reserve.end_date %></p>
      </li>
      <li>
        <p>合計金額<%= @price %>円</p>
      </li>
    </ul>
  <% end %>
</div>
  

app/views/rooms/edit.html.erb
<h1>Rooms#edit</h1>
<p>Find me in app/views/rooms/edit.html.erb</p>

app/views/rooms/index.html.erb
<h1>ルーム一覧　<%= @rooms.count%>件数</h1>

<% @rooms.each do |room| %>
  <div class = index>
    <%= link_to room_path(room), class: "index_content" do %>
      <%= image_tag room.room_img, size: '230x200', class: "index_img" %>
        <ul>
          <li class = name_address>
            <h3 class = index_name><%= room.room_name %></h3>
          </li>
          <li class = name_address>
            <%= room.address %>
          </li>
          <li>
            ￥<%= room.price %>
          </li>
        </ul>
    <% end %>
  </div>  
<% end %>

  

app/views/rooms/new.html.erb
<h3>部屋の新規登録</h3>

<%= form_with model: @room do |f| %>
  <div class = new_room>
    <ul>
      <li>
        <%= f.label :ルーム名 %><br>
        <%= f.text_field :room_name %></br>
      </li>
      <li>
        <%= f.label :ルーム紹介, class: "room_detail_tag" %><br>
        <%= f.text_area :room_detail, class: "room_detail_field" %></br>
      </li>
      <li>
        <%= f.label :料金 %><br>
        <%= f.number_field :price %></br>
      </li>
      <li>
        <%= f.label :住所 %><br>
        <%= f.text_field :address %></br>
      </li>
      <li>
        <%= f.label :ルーム画像 %><br><br>
        <%= f.file_field :room_img %></br>
      </li>
    </ul>
  </div>

  <%= f.submit "作成" %>

<% end %>

app/views/rooms/show.html.erb
<%= image_tag @room.room_img, size: '430x400', class: "show_img" %>

<div class = show_room>
  <ul>
    <li>
      <h3><%= @room.room_name %></h3>
    </li>
    <li>
      住所：<%= @room.address %>
    </li>

    <p>＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿</p>

    <li>
      <%= simple_format @room.room_detail %>
    </li>

    <p>＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿</p>

    <li>
      ￥<%= @room.price %>/１日
    </li>
  </ul>
</div>


<div class = reserve_room>
  <%= form_with model: @reserve, method: :post, url: reserves_new_path  do |f| %>  
    <%= f.hidden_field :room_id, value: @room.id %>
           
    <%= f.label :予約開始日 %>
    <%= f.date_field :start_date %>

    <%= f.label :予約終了日 %>
    <%= f.date_field :end_date %>

    <%= f.label :人数 %>
    <%= f.number_field :people %>

    <% if user_signed_in? %>
      <%= f.submit "予約確認画面へ" %>
    <% else %>
      <%=link_to new_user_session_path do %>
        <button class="btn btn-secondary btn-lg" >ログイン</button>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h3>ユーザー情報更新</h3>

<div class ="edit_view">
  <%= form_for @user do |f| %>
    <div class = user_edit>
      <ul>
        <li>
          <%= f.label :ユーザー名 %>
          <%= f.text_field :user_name %>
        </li>
        <li>
          <%= f.label :メールアドレス %>
          <%= f.text_field :email %>
        </li>
        <li>
          <%= f.label :自己紹介 %>
          <%= f.text_field :profile %>
        </li>
        <li>
          <%= f.label :アイコン画像 %>
          <%= f.file_field :user_img %><br>
        </li>
      </ul>

      <%= f.submit "更新" %>

    </div>
  <% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<p>アイコン画像</p>

<% if @user.user_img.attached? %>
  <%= image_tag current_user.user_img, size: '80x80' %>
<% else %>  
  <%= image_tag "no_image.png", size: '80x80' %>
<% end %>


<div class = user_show>
  <ul>
    <li>
      <p>名前</p>
      <%= @user.user_name %>
    </li>
    <li>
      <p>メール</p>
      <%= @user.email %>
    </li>
    <li>
      <p>プロフィール</p>
      <%= @user.profile %>
    </li>
  </ul>
</div>

<%= link_to "編集" ,edit_user_path(@user), class: "user_edit_link" %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>